### ISSUE TITLE
Filepicker.uploadLocalFile() on success FpFile always returns/converts into an image

### ISSUE THREAD

**Issue by chuyeoh** [filestack/filepicker-android#100]
I am using the Filepicker.uploadLocalFile() to manually upload "application/pdf" files to FiePicker.
However when the upload process finishes, FpFile will always return as an image

I have traced the codes in FilePicker Lib until the ContentService.java
FilesUtils returns the correct mimeType (pdf) and file name of the File Uri that I have provided.

However when being uploaded and returned, it comes back as an image. 
Uploaded image is the returned FpFile
Is there a fix to this? 

![screen shot 2016-06-01 at 11 07 28 am](https://cloud.githubusercontent.com/assets/8033594/15695393/0370fede-27ea-11e6-85ca-873f5d15adf2.png)

**Comment by stephen-workpop** [comment]
I am having the same issue. Did you ever happen to figure a solution? Thanks.

**Comment by chuyeoh** [comment]
Unfortunately not. I have contacted support and the Android developer isn't available to have a look into the issue.

**Comment by chuyeoh** [comment]
We are also having the same issue by interacting with FilePicker's api
We used the end point:
@POST https://www.filestackapi.com/api/store/S3?key=xxxx-yyyy-zzz&filename=file.pdf&path=localpath

**Comment by chuyeoh** [comment]
io.filepicker.services.ContentService.java
```
handleActionUploadFile() {
  uri = file:/data/user/0/com.homepass.agent.app/files/Section_32.pdf
  typedFile = /data/user/0/com.homepass.agent.app/files/Section_32.pdf (application/pdf)
  
  It finally calls this method at the end of this function

  FpApiClient.getFpApiClient(this).uploadFile(
                Utils.getUploadedFilename(typedFile.mimeType()),
                FpApiClient.getJsSession(this),
                typedFile,
                uploadLocalFileCallback(uri)
        );
}
```

the issue is with Utils.getUploadedFilename(typedFile.mimeType())
this is the code for that method

```
public static String getUploadedFilename(String mimetype) {
        Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("dd MMMM yyyy hh:mm a");

        String basename = (mimetype.contains("video") ? "Video " : "Image ");
        String extension = (mimetype.contains("video") ? ".mp4" : ".jpg");
        return basename + ft.format(date) + extension;
    }
```

The extension (mimetype.contains("video") ? ".mp4" : ".jpg"); this code only allows for mp4 and .jpg

the mimetype that is given is application/pdf which in this logic only return .jpg as it is not a video

Could this please be addressed quickly ?

**Comment by chuyeoh** [comment]
<img width="1274" alt="screen shot 2016-07-14 at 12 43 57 pm" src="https://cloud.githubusercontent.com/assets/8033594/16826465/e4e2aa78-49c0-11e6-9c95-bd41f589a207.png">

Uploaded stack trace of io.filepicker.utils.Utils.java
public static String getUploadedFilename(String mimetype){ ... }

**Comment by chuyeoh** [comment]
Do consider using this instead
MimeTypeMap.getFileExtensionFromUrl(file.toURI().toString())
url to file must be given instead

**Comment by stephen-workpop** [comment]
I ended up not using this library at all. Instead, I used retrofit to hit their REST API. It works very well.

**Comment by janhudzik** [comment]
Fixed in https://github.com/filestack/filepicker-android/commit/3c4a79e30e0162efc4b9100f16a159be080448a9. Will be available in 3.10.0 release.

**Comment by EAmey** [comment]
hey i m newbie for filestack I am using Filepicker.uploadLocalFile in android api but I need to set s3 location and conatiner .  Can you guys please help me on that? How i can set location using above api?

**Comment by cogKnitter** [comment]
Hi @EAmey, have you looked at the documentation on Filestack.com?
