### ISSUE TITLE
Filepicker Activity is missing toolbar/actionbar and has blurry icons

### ISSUE THREAD

**Issue by stephen-workpop** [filestack/filepicker-android#102]
Are there any extras I should be passing in to enable the toolbar? This screenshot was taken on a Nexus 6 running 6.0.1 using 'io.filepicker:filepicker-android:3.9.1'.

See screenshot: 
![filepicker](https://cloud.githubusercontent.com/assets/12835112/16603249/730b05fa-42cf-11e6-97b5-32e8705c72a5.png)

**Comment by jschnall** [comment]
Icons on Nexus 5x look bad also.

**Comment by kyuss** [comment]
We are building new library and UI. This will be addressed in that release.

**Comment by jschnall** [comment]
Running v4.0.2 on the Google Pixel now.  The icons still look blurry and terrible.
