### ISSUE TITLE
Get multiple not work

### ISSUE THREAD

**Issue by trihung93** [filestack/filepicker-android#107]
Project : io.filepicker.sample
it's just get a image .
SamSung tablet 
Model SM-T561Y
Android ver : 4.4.4

**Comment by janhudzik** [comment]
Which [service](https://github.com/filestack/filepicker-android#choosing-services) are you referring to?

What you mean by 'it's just get a image'? Do you mean it returns just a single image instead of multiple items?

**Comment by trihung93** [comment]
Yes , It returns just a single image .

**Comment by janhudzik** [comment]
For picking images from the gallery Filepicker uses installed 3rd-party applications. It starts a new activity with a native [Intent.ACTION_GET_CONTENT](https://developer.android.com/reference/android/content/Intent.html#ACTION_GET_CONTENT) action, which invokes a native gallery app or lets user choose an application if any others which can handle picking local images have been installed.

I have added an [EXTRA_ALLOW_MULTIPLE](https://developer.android.com/reference/android/content/Intent.html#EXTRA_ALLOW_MULTIPLE) parameter (commit ac03f93e60332ea7726149b8e70ade322fc80518) which indicates that intent can allow user to select and return multiple items. However please note that native gallery apps usually don't support multiple picks.

**Comment by trihung93** [comment]
thank you for your hard work.
