### ISSUE TITLE
ActionBar/Toolbar doesn't show up using custom Themes?

### ISSUE THREAD

**Issue by trihung93** [filestack/filepicker-android#108]
Hello ,

Here my Themes :
android:theme="@style/MyMaterialTheme"
```
<style name="MyMaterialTheme.Base" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimary</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowBackground">@drawable/background_splash</item>
        <item name="android:backgroundDimEnabled">false</item>
    </style>
```
So , I wanna show a toolbar and display Back Arrow on Toolbar for back to my Activity.
I think you should add a custom toolbar .
The toolbar can be customized to display exactly the items I need. I can customize the toolbar by selecting the items to include.
Tks.

<img width="430" alt="screen shot 2016-11-08 at 14 24 33" src="https://cloud.githubusercontent.com/assets/5199109/20090358/4100021a-a5bf-11e6-82c7-2051927642c5.png">

**Comment by janhudzik** [comment]
It is developer's responsibility to implement the toolbar in his application. Filepicker just provides a single activity, while the toolbar should be consistent across all the activities of the application.
