### ISSUE TITLE
FilePickerTheme not set in manifest

### ISSUE THREAD

**Issue by SleeplessByte** [filestack/filepicker-android#51]
Set it, or "Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity."

**Comment by maciejwitowski** [comment]
My point of view: not setting theme in Filepicker Library and making the app which uses it select the theme is the correct approach, so I don't think a change is needed here.

Am I right?

**Comment by SleeplessByte** [comment]
No.

When there is no theme set, the theme that will be used will always be a theme from the android project (not the library project), without a default.

Having a default and making it over-ridable sound way better. Or at least put in the documentation that one MUST set the theme.

**Comment by SleeplessByte** [comment]
This is still not resolved. Please don't use the generic `AppTheme` name, but something namespaced like FilePickerAppTheme`

**Comment by janhudzik** [comment]
Fixed in bb4efc2df009adf81b538934c558ba4371d20537. Will be avaialbe in 3.10.0 release.
