### ISSUE TITLE
Row icons for large screens

### ISSUE THREAD

**Issue by marcoRS** [filestack/filepicker-android#60]
Hello, 
        Is it possible to include different service icons by resource buckets ie, drawable-xxhdpi, drawable-xhdpi, etc... The icons start looking very pixelated  when viewing FilePicker on larger devices. 

Have you guys also considered using a GridView vs Listview on larger devices such as tablets? 

![filepicker](https://cloud.githubusercontent.com/assets/507510/5685354/4b7df32c-97ee-11e4-90e6-eb8116107732.png)

**Comment by maciejwitowski** [comment]
Hi Marco,

About icons: We are planning in the next months, to make a new UI for Filepicker web dialog and then all the  icons on mobile as well will be change to higher quality.

About grid view: this will be a good idea for the future (general optimization of the library for tablets), it isn't in our nearest plans though.

**Comment by marcoRS** [comment]
Any updates on this? I don't mean to sound picky, Filepicker is great but the UI for Android could use a lot of love and especially the icons....

**Comment by dbaq** [comment]
:+1:

**Comment by michaelelias** [comment]
+1

**Comment by kyuss** [comment]
We are working on new library and UI for Android. This will be addressed in that release.
