### ISSUE TITLE
Unable to find URL of uploaded file

### ISSUE THREAD

**Issue by Skilledpeas2209** [filestack/filepicker-android#74]
File is uploaded successfully but i am not able to get the URL of file uploaded on Filepicker.
i dont want any operation on that just the URL.
Sample code creates FpFile object and stores Parcelable response to it but creating that object returns me nullpointer.

**Comment by maciejwitowski** [comment]
@Skilledpeas2209 is this issue still valid?

Can you give more details? Like:
- from where are you uploading the picture? (camera? gallery?)
- can you paste the code you use?
