### ISSUE TITLE
Image search not available 

### ISSUE THREAD

**Issue by chgsilva** [filestack/filepicker-android#85]
I am using file picker in order to build my app. For the web version and in the  iOS version of the file picker, it has the option to make an image search. But for the android version of the file picker, it doesn’t. Someone have some workaround for this issue?

**Comment by martha444** [comment]
Hi chgsilva,

We do not have any workaround but I will share your idea with our engineers for their consideration.
Thanks.

**Comment by kyuss** [comment]
We are building a new library and UI for Android. This will be addressed in that release.
