### ISSUE TITLE
Unable to upload from URL to specified location

### ISSUE THREAD

**Issue by 6ameDev** [filestack/filepicker-android#97]
Like in a web app we can use `exportFile()` and pass `url` and `service` (DROPBOX, GOOGLE_DRIVE).
The docs don't mention anything on the similar lines, if I want to upload a file directly from some URL to dropbox or any other service, how would that be done.

PS:
I looked into the code and got this far, **ContentService.java** *Line 171*:

```
FPFile result = FpApiClient.getFpApiClient(this).pickFile(
                        URLDecoder.decode(node.linkPath, "utf-8"),
                        "fpurl",
                        FpApiClient.getJsSession(this));
```

If I pick a file from Dropbox, node.linkPath comes out to be something like 
`/Dropbox/Images/Blah.png`
If I were to take the same approach for uploading files from URLs, I would have to somehow replace that path and make it work with
`https://www.dropbox.com/home/Images/Blah.png`

Any help would be much appreciated.

**Comment by kyuss** [comment]
We are building new version of the library and UI. This will be addressed in that release.
